title: Personal Blog
description: My views on technology, coding, global affairs, economy, travel and more
url: https://shisuiuchiha.github.io/

markdown: kramdown
permalink: /posts/:title/
theme: jekyll-theme-minimal

future: true